### ISSUE TITLE
implementing a trait with methods that return Self 

### ISSUE THREAD

**Issue by joseluis** [upsuper/delegate-attr#7]
This crate doesn't seem to work for implementing traits with methods returning Self, because of mistmatched types, expecting the same type for the self parameter and for the output.

Do you think a fix is possible so that it can return the inner type in that case?

**Comment by upsuper** [comment]
I'm not sure I understand your requirement. Do you have a concrete example showing what you want the crate to do?

**Comment by joseluis** [comment]
Ok this would be a minimal example of what I'm talking about:

```rust
// ---

trait Chainable {
    fn make1(self) -> Self;
}

struct Chain(u8);

impl Chainable for Chain {
    fn make1(mut self) -> Self {
        self.0 = 1;
        self
    }
}

// ---

use delegate_attr::delegate;

struct WrappedChain(Chain);

#[delegate(self.0)]
impl Chainable for WrappedChain {
    fn make1(mut self) -> Self;
}

fn main() {}
```

Fails with:
```shell
22 | #[delegate(self.0)]
   | ^^^^^^^^^^^^^^^^^^^ expected struct `WrappedChain`, found struct `Chain`
23 | impl Chainable for WrappedChain {
24 |     fn make1(mut self) -> Self;
   |                           ---- expected `WrappedChain` because of return type
```

**Comment by upsuper** [comment]
How would you write the code without the procedural macro? Macro is ultimately just a way to automate generating boilerplate code. It can't magically make some code which doesn't compile compile.

**Comment by joseluis** [comment]
Ok I see, I'm not yet very familiar with the limits of what procedural macros can do. I guess it's not possible then... Thanks for the quick response.

The only "solution" I can think of is... once returning impl Trait from a trait becomes possible, the original trait could be written as:

```rust
trait Chainable {
    fn make1(self) -> impl Chainable;
}
```
Right now it fails with:
```shell
error[E0562]: `impl Trait` not allowed outside of function and method return types
 --> examples/issue-7.rs:4:23
  |
4 |     fn make1(self) -> impl Chainable;
  |                       ^^^^^^^^^^^^^^
```

Closing
